from django.urls import path

from xsys.api_views_socios import (
    SocioContratosAPI,
    SocioCuentaCorrienteAPI,
    SocioFichaAPI,
    SocioGrupoFamiliarAPI,
    SociosListadoAPI,
)
from xsys.api_views_tableros import (
    TableroAltasBajasAPI,
    TableroCategoriasAPI,
    TableroDeudaAPI,
    TableroDeudaDetalleAPI,
    TableroDeudaDetalleExcelAPI,
    TableroDeudaEstadoAPI,
    TableroDeudaExcelAPI,
    TableroDeudaRecalcularAPI,
    TableroPadronAPI,
)
from xsys.api_views import (
    AccesoResolverAPI,
    AccesosBuscarAPI,
    BiostarDevicesCatalogAPI,
    ControladoresXsysAPI,
    DiagnosticoAccesoAPI,
    MolineteConfigDetailAPI,
    MolinetesAutoAPI,
    MolinetesConfigAPI,
    PuertaConfigDetailAPI,
    PuertaControladoresAPI,
    PuertaEstadoAPI,
    PuertaHistorialAPI,
    PuertaSeleccionarAPI,
    PuertasConfigAPI,
    PuertasListAPI,
    PantallaAvisoAPI,
    SocioAccesosAPI,
    SocioDetalleAPI,
    SocioFotoAPI,
    SocioLookupAPI,
    SocioSearchAPI,
    SocioWhitelistAPI,
)

urlpatterns = [
    # Tableros de gestión (rol tableros).
    path("xsys/tableros/padron/", TableroPadronAPI.as_view(), name="xsys_tablero_padron_api"),
    path("xsys/tableros/altas-bajas/", TableroAltasBajasAPI.as_view(),
         name="xsys_tablero_altas_bajas_api"),
    path("xsys/tableros/categorias/", TableroCategoriasAPI.as_view(),
         name="xsys_tablero_categorias_api"),
    path("xsys/tableros/deuda/", TableroDeudaAPI.as_view(), name="xsys_tablero_deuda_api"),
    path("xsys/tableros/deuda/recalcular/", TableroDeudaRecalcularAPI.as_view(),
         name="xsys_tablero_deuda_recalcular_api"),
    path("xsys/tableros/deuda/estado/", TableroDeudaEstadoAPI.as_view(),
         name="xsys_tablero_deuda_estado_api"),
    path("xsys/tableros/deuda/excel/", TableroDeudaExcelAPI.as_view(),
         name="xsys_tablero_deuda_excel_api"),
    path("xsys/tableros/deuda/detalle/", TableroDeudaDetalleAPI.as_view(),
         name="xsys_tablero_deuda_detalle_api"),
    path("xsys/tableros/deuda/detalle/excel/", TableroDeudaDetalleExcelAPI.as_view(),
         name="xsys_tablero_deuda_detalle_excel_api"),
    path("xsys/acceso/", AccesoResolverAPI.as_view(), name="xsys_acceso_api"),
    path("xsys/diagnostico/", DiagnosticoAccesoAPI.as_view(), name="xsys_diagnostico_api"),
    path("xsys/puertas/", PuertasListAPI.as_view(), name="xsys_puertas_api"),
    path("xsys/puerta/estado/", PuertaEstadoAPI.as_view(), name="xsys_puerta_estado_api"),
    path("xsys/puerta/historial/", PuertaHistorialAPI.as_view(), name="xsys_puerta_historial_api"),
    path("xsys/accesos/buscar/", AccesosBuscarAPI.as_view(), name="xsys_accesos_buscar_api"),
    path("xsys/puerta/seleccionar/", PuertaSeleccionarAPI.as_view(), name="xsys_puerta_seleccionar_api"),
    # Armado de puertas (requiere login): puerta -> controladores -> molinetes.
    path("xsys/config/puertas/", PuertasConfigAPI.as_view(), name="xsys_config_puertas_api"),
    path("xsys/config/puertas/<int:pid>/", PuertaConfigDetailAPI.as_view(), name="xsys_config_puerta_detail_api"),
    path("xsys/config/puertas/<int:pid>/controladores/", PuertaControladoresAPI.as_view(), name="xsys_config_puerta_controladores_api"),
    path("xsys/config/controladores-xsys/", ControladoresXsysAPI.as_view(), name="xsys_config_controladores_xsys_api"),
    path("xsys/config/biostar-devices/", BiostarDevicesCatalogAPI.as_view(), name="xsys_config_biostar_devices_api"),
    path("xsys/config/molinetes/", MolinetesConfigAPI.as_view(), name="xsys_config_molinetes_api"),
    path("xsys/config/molinetes/auto/", MolinetesAutoAPI.as_view(), name="xsys_config_molinetes_auto_api"),
    path("xsys/config/molinetes/<int:mid>/", MolineteConfigDetailAPI.as_view(), name="xsys_config_molinete_detail_api"),
    path("xsys/socios/lookup/", SocioLookupAPI.as_view(), name="xsys_socio_lookup_api"),
    # Pantalla de fichas de socios (rol socios).
    path("xsys/socios/listado/", SociosListadoAPI.as_view(), name="xsys_socios_listado_api"),
    path("xsys/socios/<int:id_cliente>/ficha/", SocioFichaAPI.as_view(), name="xsys_socio_ficha_api"),
    path("xsys/socios/<int:id_cliente>/cuenta-corriente/", SocioCuentaCorrienteAPI.as_view(),
         name="xsys_socio_ctacte_api"),
    path("xsys/socios/<int:id_cliente>/grupo-familiar/", SocioGrupoFamiliarAPI.as_view(),
         name="xsys_socio_grupo_api"),
    path("xsys/socios/<int:id_cliente>/contratos/", SocioContratosAPI.as_view(),
         name="xsys_socio_contratos_api"),
    path("xsys/socios/", SocioSearchAPI.as_view(), name="xsys_socio_search_api"),
    path("xsys/socios/<int:id_cliente>/detalle/", SocioDetalleAPI.as_view(), name="xsys_socio_detalle_api"),
    path("xsys/socios/<int:id_cliente>/accesos/", SocioAccesosAPI.as_view(), name="xsys_socio_accesos_api"),
    path("xsys/socios/<int:id_cliente>/aviso/", PantallaAvisoAPI.as_view(), name="xsys_socio_aviso_api"),
    path("xsys/socios/<int:id_cliente>/whitelist/", SocioWhitelistAPI.as_view(), name="xsys_socio_whitelist_api"),
    path("xsys/socios/<int:id_cliente>/foto/", SocioFotoAPI.as_view(), name="xsys_socio_foto_api"),
]
