# Generated by Django 5.1.15 on 2026-07-18 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=40, unique=True)),
                ('last_id', models.BigIntegerField(blank=True, null=True)),
                ('last_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_run_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_ok', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('rows_last_run', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estado de sincronización xSys',
                'verbose_name_plural': 'Estados de sincronización xSys',
                'db_table': 'xsys_sync_state',
            },
        ),
        migrations.CreateModel(
            name='XsysNovedad',
            fields=[
                ('id_novedad', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(db_index=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('estado_origen', models.CharField(blank=True, default='', max_length=1)),
                ('tipo', models.CharField(blank=True, default='', max_length=1)),
                ('nota', models.CharField(blank=True, default='', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Novedad de socio (xSys)',
                'verbose_name_plural': 'Novedades de socios (xSys)',
                'db_table': 'xsys_novedad',
                'ordering': ('-id_novedad',),
            },
        ),
        migrations.CreateModel(
            name='XsysSocio',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_nro', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('apellido', models.CharField(blank=True, default='', max_length=100)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('razon_social', models.CharField(blank=True, default='', max_length=100)),
                ('sexo', models.CharField(blank=True, default='', max_length=1)),
                ('fecha_nac', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=600)),
                ('activo', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('tipo_persona', models.CharField(blank=True, default='', max_length=1)),
                ('credencial_nro', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('ult_cuota_paga', models.DateTimeField(blank=True, null=True)),
                ('id_estado_cliente', models.SmallIntegerField(blank=True, null=True)),
                ('id_cliente_externo', models.CharField(blank=True, default='', max_length=14)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Socio (xSys)',
                'verbose_name_plural': 'Socios (xSys)',
                'db_table': 'xsys_socio',
                'ordering': ('apellido', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='XsysSocioFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(db_index=True)),
                ('nro', models.PositiveSmallIntegerField()),
                ('imagen', models.BinaryField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Foto de socio (xSys)',
                'verbose_name_plural': 'Fotos de socios (xSys)',
                'db_table': 'xsys_socio_foto',
                'constraints': [models.UniqueConstraint(fields=('id_cliente', 'nro'), name='uniq_xsys_foto_cliente_nro')],
            },
        ),
        migrations.CreateModel(
            name='XsysWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(db_index=True, unique=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('motivo_code', models.IntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=120)),
                ('detalle', models.CharField(blank=True, default='', max_length=120)),
                ('id_acceso', models.IntegerField(blank=True, null=True)),
                ('fecha_calculo', models.DateTimeField(default=django.utils.timezone.now)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Lista blanca general (xSys)',
                'verbose_name_plural': 'Lista blanca general (xSys)',
                'db_table': 'xsys_whitelist',
                'indexes': [models.Index(fields=['habilitado'], name='xsys_whitel_habilit_bb9dd3_idx')],
            },
        ),
    ]
