# Generated by Django 5.1.15 on 2026-07-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsyssociofoto',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
