# Generated by Django 5.1.15 on 2026-07-18 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0002_xsyssociofoto_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PantallaPuerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('id_acceso', models.IntegerField(blank=True, db_index=True, null=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=60)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Pantalla / puesto (por token)',
                'verbose_name_plural': 'Pantallas / puestos (por token)',
                'db_table': 'xsys_pantalla_puerta',
                'ordering': ('nombre', 'token'),
            },
        ),
        migrations.CreateModel(
            name='XsysAcceso',
            fields=[
                ('id_acceso', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, default='', max_length=40)),
                ('descripcion_corta', models.CharField(blank=True, default='', max_length=20)),
                ('activo', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Acceso / puerta (xSys)',
                'verbose_name_plural': 'Accesos / puertas (xSys)',
                'db_table': 'xsys_acceso',
                'ordering': ('descripcion',),
            },
        ),
        migrations.CreateModel(
            name='XsysMotivo',
            fields=[
                ('id_cd_motivo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, default='', max_length=1)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('descripcion_display', models.CharField(blank=True, default='', max_length=32)),
                ('descripcion_pantalla', models.CharField(blank=True, default='', max_length=100)),
                ('activo', models.SmallIntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Motivo de acceso (xSys)',
                'verbose_name_plural': 'Motivos de acceso (xSys)',
                'db_table': 'xsys_motivo',
            },
        ),
    ]
