# Generated by Django 5.1.15 on 2026-07-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0003_pantallapuerta_xsysacceso_xsysmotivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantallapuerta',
            name='id_acceso',
        ),
        migrations.AddField(
            model_name='pantallapuerta',
            name='id_accesos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
