# Generated by Django 5.2.16 on 2026-07-18 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0004_remove_pantallapuerta_id_acceso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuertaMolinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_acceso', models.IntegerField(db_index=True)),
                ('nombre', models.CharField(max_length=60)),
                ('id_controladores', models.JSONField(default=list)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Molinete (columna del monitor)',
                'verbose_name_plural': 'Molinetes (columnas del monitor)',
                'db_table': 'xsys_puerta_molinete',
                'ordering': ('id_acceso', 'orden', 'id'),
            },
        ),
        migrations.CreateModel(
            name='XsysControlador',
            fields=[
                ('id_controlador', models.IntegerField(primary_key=True, serialize=False)),
                ('id_acceso', models.IntegerField(db_index=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=100)),
                ('tipo', models.CharField(blank=True, default='', max_length=1)),
                ('tipo_cont', models.CharField(blank=True, default='', max_length=1)),
                ('activo', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Controlador / molinete (xSys)',
                'verbose_name_plural': 'Controladores / molinetes (xSys)',
                'db_table': 'xsys_controlador',
                'ordering': ('id_acceso', 'descripcion'),
            },
        ),
        migrations.RemoveField(
            model_name='pantallapuerta',
            name='id_accesos',
        ),
        migrations.AddField(
            model_name='pantallapuerta',
            name='id_acceso',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
