# Generated by Django 5.2.16 on 2026-07-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0005_puertamolinete_xsyscontrolador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsyssocio',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
