# Generated by Django 5.2.16 on 2026-07-18 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0006_xsyssocio_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='XsysContrato',
            fields=[
                ('id_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(db_index=True)),
                ('id_tipo_con', models.SmallIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('fecha_hasta', models.DateTimeField(blank=True, null=True)),
                ('activo', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Contrato de socio (xSys)',
                'verbose_name_plural': 'Contratos de socios (xSys)',
                'db_table': 'xsys_contrato',
                'ordering': ('id_cliente', 'descripcion'),
            },
        ),
    ]
