# Generated by Django 5.2.16 on 2026-07-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0007_xsyscontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xsysnovedad',
            name='id_cliente',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
