# Generated by Django 5.2.12 on 2026-07-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_accessdoor_options_and_more'),
        ('xsys', '0007_xsyscontrato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PuertaMolinete',
        ),
        migrations.RemoveField(
            model_name='pantallapuerta',
            name='id_acceso',
        ),
        migrations.AddField(
            model_name='pantallapuerta',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pantallas', to='institutions.accessdoor'),
        ),
    ]
