# Generated by Django 5.2.12 on 2026-07-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0008_delete_puertamolinete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsyscontrolador',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='IP'),
        ),
    ]
