# Generated by Django 5.2.16 on 2026-07-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0008_alter_xsysnovedad_id_cliente'),
        ('xsys', '0009_xsyscontrolador_ip'),
    ]

    operations = [
    ]
