# Generated by Django 5.2.16 on 2026-08-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0010_merge_20260722_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsyscontrato',
            name='deuda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='xsyscontrato',
            name='producto_desc',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='xsyscontrato',
            name='ultimo_cbte_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xsyscontrato',
            name='ultimo_pago_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xsyscontrato',
            name='ultimo_pago_importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
