# Generated by Django 5.2.16 on 2026-08-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0011_xsyscontrato_deuda_xsyscontrato_producto_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsyssocio',
            name='id_cliente_ref',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
