# Generated by Django 5.2.16 on 2026-08-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0012_xsyssocio_id_cliente_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsysacceso',
            name='flag_ult_cuota_paga',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
