# Generated by Django 5.2.16 on 2026-08-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0013_xsysacceso_flag_ult_cuota_paga'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsyssocio',
            name='id_tipo_cli',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
