# Generated by Django 5.2.16 on 2026-08-31 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0014_socio_id_tipo_cli'),
    ]

    operations = [
        migrations.CreateModel(
            name='XsysBajaRevision',
            fields=[
                ('id_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('origen', models.CharField(blank=True, default='', max_length=60)),
                ('en_revision', models.BooleanField(db_index=True, default=True)),
                ('fecha_baja_orig', models.DateTimeField(blank=True, null=True)),
                ('motivo_orig', models.SmallIntegerField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, default='', max_length=200)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Baja en revisión',
                'verbose_name_plural': 'Bajas en revisión',
                'db_table': 'xsys_baja_revision',
            },
        ),
    ]
