# Generated by Django 5.2.16 on 2026-09-02 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0015_baja_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='XsysDeudaActividades',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('cuotas', models.SmallIntegerField(blank=True, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actividad', models.CharField(blank=True, default='', max_length=60)),
                ('bloquea', models.BooleanField(db_index=True, default=False)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('origen', models.CharField(blank=True, default='', max_length=60)),
                ('observacion', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Deuda de actividades (xSys)',
                'verbose_name_plural': 'Deudas de actividades (xSys)',
                'db_table': 'xsys_deuda_actividades',
                'ordering': ('-bloquea', 'id_cliente'),
            },
        ),
    ]
