# Generated by Django 5.2.16 on 2026-09-07 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0016_xsysdeudaactividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='XsysSocioEdicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(db_index=True)),
                ('campo', models.CharField(max_length=60)),
                ('etiqueta', models.CharField(blank=True, default='', max_length=80)),
                ('valor_anterior', models.CharField(blank=True, default='', max_length=255)),
                ('valor_nuevo', models.CharField(blank=True, default='', max_length=255)),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
                ('ip', models.CharField(blank=True, default='', max_length=45)),
                ('creado_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Edición de ficha (xSys)',
                'verbose_name_plural': 'Ediciones de fichas (xSys)',
                'db_table': 'xsys_socio_edicion',
                'ordering': ('-creado_at', '-id'),
                'indexes': [models.Index(fields=['id_cliente', '-creado_at'], name='xsys_socio_edic_cli')],
            },
        ),
    ]
