# Generated by Django 5.2.16 on 2026-09-08 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0017_xsyssocioedicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='XsysDeudaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculado_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usuario', models.CharField(blank=True, default='', max_length=150)),
                ('ok', models.BooleanField(db_index=True, default=False)),
                ('duracion_ms', models.IntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('socios', models.IntegerField(default=0)),
                ('cupones', models.IntegerField(default=0)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'verbose_name': 'Foto de deuda (xSys)',
                'verbose_name_plural': 'Fotos de deuda (xSys)',
                'db_table': 'xsys_deuda_foto',
                'ordering': ('-calculado_at',),
            },
        ),
        migrations.CreateModel(
            name='XsysDeudaMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(db_index=True)),
                ('id_tipo_cli', models.IntegerField(blank=True, db_index=True, null=True)),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('es_socio', models.BooleanField(db_index=True, default=False)),
                ('activo', models.BooleanField(db_index=True, default=False)),
                ('socios', models.IntegerField(default=0)),
                ('cupones', models.IntegerField(default=0)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meses', to='xsys.xsysdeudafoto')),
            ],
            options={
                'verbose_name': 'Deuda por mes (xSys)',
                'verbose_name_plural': 'Deuda por mes (xSys)',
                'db_table': 'xsys_deuda_mes',
                'ordering': ('mes', 'categoria'),
                'indexes': [models.Index(fields=['foto', 'mes'], name='xsys_deuda_mes_foto')],
            },
        ),
        migrations.CreateModel(
            name='XsysDeudaSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(db_index=True)),
                ('nro_socio', models.CharField(blank=True, default='', max_length=14)),
                ('doc_nro', models.BigIntegerField(blank=True, null=True)),
                ('apellido', models.CharField(blank=True, default='', max_length=100)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('id_tipo_cli', models.IntegerField(blank=True, db_index=True, null=True)),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('es_socio', models.BooleanField(db_index=True, default=False)),
                ('activo', models.BooleanField(db_index=True, default=False)),
                ('cuotas', models.IntegerField(db_index=True, default=0)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mes_mas_viejo', models.DateField(blank=True, null=True)),
                ('mes_mas_nuevo', models.DateField(blank=True, null=True)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios_deuda', to='xsys.xsysdeudafoto')),
            ],
            options={
                'verbose_name': 'Deuda por socio (xSys)',
                'verbose_name_plural': 'Deuda por socio (xSys)',
                'db_table': 'xsys_deuda_socio',
                'ordering': ('-importe',),
                'indexes': [models.Index(fields=['foto', '-importe'], name='xsys_deuda_soc_imp'), models.Index(fields=['foto', 'cuotas'], name='xsys_deuda_soc_cuo')],
            },
        ),
    ]
