# Generated by Django 5.2.17 on 2026-09-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0018_xsysdeudafoto_xsysdeudames_xsysdeudasocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsysdeudames',
            name='rubro',
            field=models.CharField(db_index=True, default='otros', max_length=20),
        ),
        migrations.AddField(
            model_name='xsysdeudasocio',
            name='cuotas_actividades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xsysdeudasocio',
            name='cuotas_cuota_social',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xsysdeudasocio',
            name='importe_actividades',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='xsysdeudasocio',
            name='importe_cuota_social',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='xsysdeudasocio',
            name='importe_otros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
