# Generated by Django 5.2.17 on 2026-09-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0019_xsysdeudames_rubro_xsysdeudasocio_cuotas_actividades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsysdeudames',
            name='actividad',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
    ]
