# Generated by Django 5.2.17 on 2026-09-08 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0020_xsysdeudames_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='XsysDeudaSocioActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('cuotas', models.IntegerField(default=0)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mes_mas_viejo', models.DateField(blank=True, null=True)),
                ('mes_mas_nuevo', models.DateField(blank=True, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='xsys.xsysdeudasocio')),
            ],
            options={
                'verbose_name': 'Deuda por socio y actividad (xSys)',
                'verbose_name_plural': 'Deuda por socio y actividad (xSys)',
                'db_table': 'xsys_deuda_socio_actividad',
                'ordering': ('-importe',),
                'indexes': [models.Index(fields=['actividad', '-importe'], name='xsys_deuda_act_imp')],
            },
        ),
    ]
