# Generated by Django 5.2.17 on 2026-09-08 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsys', '0021_xsysdeudasocioactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='XsysDeudaSocioMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(db_index=True)),
                ('rubro', models.CharField(db_index=True, default='otros', max_length=20)),
                ('actividad', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('cuotas', models.IntegerField(default=0)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='xsys.xsysdeudasocio')),
            ],
            options={
                'verbose_name': 'Deuda por socio y mes (xSys)',
                'verbose_name_plural': 'Deuda por socio y mes (xSys)',
                'db_table': 'xsys_deuda_socio_mes',
                'ordering': ('mes',),
            },
        ),
        migrations.DeleteModel(
            name='XsysDeudaSocioActividad',
        ),
        migrations.AddIndex(
            model_name='xsysdeudasociomes',
            index=models.Index(fields=['actividad', 'mes'], name='xsys_deuda_sm_act'),
        ),
        migrations.AddIndex(
            model_name='xsysdeudasociomes',
            index=models.Index(fields=['rubro', 'mes'], name='xsys_deuda_sm_rub'),
        ),
    ]
