# Generated by Django 5.2.16 on 2026-09-01 23:32

import concesionarios.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Horario de acceso',
                'verbose_name_plural': 'Horarios de acceso',
                'db_table': 'conc_horario',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('requiere_vencimiento', models.BooleanField(default=True)),
                ('dias_aviso', models.PositiveIntegerField(default=30, help_text='Días antes del vencimiento en que se avisa que está por vencer.')),
                ('bloquea_acceso', models.BooleanField(default=False)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'db_table': 'conc_tipo_documento',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('cuit', models.CharField(blank=True, default='', max_length=20)),
                ('rubro', models.CharField(blank=True, default='', max_length=80)),
                ('contacto_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('contacto_email', models.CharField(blank=True, default='', max_length=200)),
                ('contacto_telefono', models.CharField(blank=True, default='', max_length=60)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='concesionarios.horarioacceso')),
            ],
            options={
                'verbose_name': 'Empresa concesionaria',
                'verbose_name_plural': 'Empresas concesionarias',
                'db_table': 'conc_empresa',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Concesionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(db_index=True, unique=True)),
                ('cargo', models.CharField(blank=True, default='', max_length=80)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concesionarios', to='concesionarios.empresa')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concesionarios', to='concesionarios.horarioacceso')),
            ],
            options={
                'verbose_name': 'Concesionario',
                'verbose_name_plural': 'Concesionarios',
                'db_table': 'conc_concesionario',
                'ordering': ('empresa__nombre', 'id_cliente'),
            },
        ),
        migrations.CreateModel(
            name='HorarioFranja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.SmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franjas', to='concesionarios.horarioacceso')),
            ],
            options={
                'verbose_name': 'Franja horaria',
                'verbose_name_plural': 'Franjas horarias',
                'db_table': 'conc_horario_franja',
                'ordering': ('dia_semana', 'hora_desde'),
                'unique_together': {('horario', 'dia_semana', 'hora_desde', 'hora_hasta')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(db_index=True)),
                ('numero', models.CharField(blank=True, default='', max_length=64)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=concesionarios.models.ruta_documento)),
                ('archivo_nombre', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, null=True)),
                ('observaciones', models.CharField(blank=True, default='', max_length=300)),
                ('subido_por', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='concesionarios.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'conc_documento',
                'ordering': ('fecha_vencimiento', 'tipo__nombre'),
                'indexes': [models.Index(fields=['id_cliente', 'fecha_vencimiento'], name='conc_docume_id_clie_bbe407_idx')],
            },
        ),
    ]
