# Generated by Django 5.2.16 on 2026-09-02 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionarios', '0003_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(db_index=True, unique=True)),
                ('imagen', models.BinaryField()),
                ('thumbnail', models.BinaryField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='image/jpeg', max_length=60)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('subido_por', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrolada_at', models.DateTimeField(blank=True, null=True)),
                ('enrolada_resultado', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Foto cargada',
                'verbose_name_plural': 'Fotos cargadas',
                'db_table': 'conc_foto_persona',
                'ordering': ('-created_at',),
            },
        ),
    ]
