# Generated by Django 5.1.15 on 2026-01-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioStar2Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('username', models.CharField(max_length=150)),
                ('bs_session_id', models.CharField(blank=True, default='', max_length=512)),
                ('session_obtained_at', models.DateTimeField(blank=True, null=True)),
                ('verify_tls', models.BooleanField(default=False)),
                ('timeout_seconds', models.PositiveIntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BioStar 2 Config',
                'verbose_name_plural': 'BioStar 2 Config',
            },
        ),
        migrations.CreateModel(
            name='BioStarDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('device_type', models.CharField(blank=True, default='', max_length=100)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BioStar Device',
                'verbose_name_plural': 'BioStar Devices',
            },
        ),
    ]
