# Generated by Django 5.1.15 on 2026-01-19 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_biostaruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioStarDeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BioStar Device Group',
                'verbose_name_plural': 'BioStar Device Groups',
            },
        ),
        migrations.AddField(
            model_name='biostardevice',
            name='device_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='access_control.biostardevicegroup'),
        ),
    ]
