# Generated by Django 5.1.15 on 2026-01-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0004_biostardevicegroup_biostardevice_device_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="biostaruser",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="biostaruser",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
