# Generated by Django 5.1.15 on 2026-01-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0005_biostaruser_activity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="whitelistentry",
            name="days_of_week",
            field=models.JSONField(
                blank=True,
                help_text="Lista de días de la semana (0=Lunes, 6=Domingo) para recurrencia semanal.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whitelistentry",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="whitelistentry",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
