# Generated by Django 5.1.15 on 2026-03-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "access_control",
            "0006_whitelistentry_days_of_week_whitelistentry_end_time_and_more",
        ),
        ("institutions", "0002_accessdoor_accesszone_doordevice_doorzonecontrol"),
        ("people", "0003_documenttype_personcategory_person_person_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("source", models.CharField(default="manual", max_length=32)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_events",
                        to="people.personcategory",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_events",
                        to="people.person",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_events",
                        to="institutions.site",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at",),
                "indexes": [
                    models.Index(
                        fields=["site", "occurred_at"],
                        name="access_cont_site_id_3511df_idx",
                    ),
                    models.Index(
                        fields=["category", "occurred_at"],
                        name="access_cont_categor_6b392a_idx",
                    ),
                ],
            },
        ),
    ]
