# Generated by Django 5.1.15 on 2026-03-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0007_accessevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.BigIntegerField()),
                ("patente", models.CharField(max_length=16)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("entry", "Ingreso"), ("exit", "Salida")],
                        max_length=10,
                    ),
                ),
                ("ult_cuota_paga", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Movimiento de estacionamiento",
                "verbose_name_plural": "Movimientos de estacionamiento",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["dni", "-created_at"], name="access_cont_dni_95f897_idx"
                    ),
                    models.Index(
                        fields=["patente", "-created_at"],
                        name="access_cont_patente_1f969f_idx",
                    ),
                ],
            },
        ),
    ]
