# Generated by Django 5.1.15 on 2026-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0008_parkingmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingmovement",
            name="exit_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parkingmovement",
            name="stay_duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
