# Generated by Django 5.2.13 on 2026-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0010_ansesverificationrecord"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ansesverificationrecord",
            new_name="access_cont_request_e6b7fe_idx",
            old_name="access_contr_request_491766_idx",
        ),
        migrations.RenameIndex(
            model_name="ansesverificationrecord",
            new_name="access_cont_request_2ed647_idx",
            old_name="access_contr_request_44ecf5_idx",
        ),
        migrations.AddField(
            model_name="ansesverificationrecord",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ansesverificationrecord",
            name="verification_message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="ansesverificationrecord",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("generated", "Constancia generada"),
                    ("office_required", "Validar identidad en oficina ANSES"),
                    ("unknown", "Resultado no identificado"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
    ]
