# Generated by Django 5.2.13 on 2026-04-15 00:00

from django.db import migrations, models


def reset_existing_anses_records(apps, schema_editor):
    AnsesVerificationRecord = apps.get_model("access_control", "AnsesVerificationRecord")
    AnsesVerificationRecord.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0011_rename_access_contr_request_491766_idx_access_cont_request_e6b7fe_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ansesverificationrecord",
            name="apellido",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="ansesverificationrecord",
            name="edad",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ansesverificationrecord",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ansesverificationrecord",
            name="nombre",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.RunPython(reset_existing_anses_records, migrations.RunPython.noop),
    ]
