# Generated by Django 5.2.16 on 2026-07-24 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0013_ansesverificationrecord_deceased_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiostarAccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biostar_id', models.CharField(max_length=40, unique=True)),
                ('device_id', models.BigIntegerField(db_index=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('id_cliente', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('fecha', models.DateTimeField(db_index=True)),
                ('event_code', models.IntegerField(blank=True, null=True)),
                ('event_name', models.CharField(blank=True, default='', max_length=120)),
                ('permitido', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Evento de acceso BioStar',
                'verbose_name_plural': 'Eventos de acceso BioStar',
                'db_table': 'biostar_access_event',
                'ordering': ('-fecha', '-id'),
                'indexes': [models.Index(fields=['device_id', '-fecha'], name='biostar_acc_device__ab5eef_idx'), models.Index(fields=['-fecha'], name='biostar_acc_fecha_222f08_idx')],
            },
        ),
    ]
