# Generated by Django 5.2.16 on 2026-07-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0014_biostaraccessevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiostarPollState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_event_id', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'biostar_poll_state',
            },
        ),
    ]
