# Generated by Django 5.2.16 on 2026-07-28 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0015_biostarpollstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelektronEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=80, unique=True)),
                ('device_ip', models.CharField(db_index=True, max_length=40)),
                ('dest_node', models.IntegerField(default=1)),
                ('id_controlador', models.IntegerField(blank=True, db_index=True, null=True)),
                ('access_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('event_code', models.IntegerField(blank=True, null=True)),
                ('event_name', models.CharField(blank=True, default='', max_length=60)),
                ('direction', models.IntegerField(blank=True, null=True)),
                ('direction_name', models.CharField(blank=True, default='', max_length=60)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('device_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Evento Intelektron',
                'verbose_name_plural': 'Eventos Intelektron',
                'db_table': 'intelektron_event',
                'ordering': ('-device_time', '-id'),
                'indexes': [models.Index(fields=['device_ip', '-device_time'], name='intelektron_device__34b9eb_idx'), models.Index(fields=['-created_at'], name='intelektron_created_dd747f_idx')],
            },
        ),
    ]
