# Generated by Django 5.2.16 on 2026-08-03 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0016_intelektronevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioAviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.BigIntegerField(db_index=True)),
                ('tipo', models.CharField(default='libre', max_length=32)),
                ('texto', models.CharField(max_length=500)),
                ('creado_por', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Aviso de socio',
                'verbose_name_plural': 'Avisos de socios',
                'db_table': 'socio_aviso',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['id_cliente', '-created_at'], name='socio_aviso_id_clie_99a565_idx')],
            },
        ),
    ]
