# Generated by Django 5.2.16 on 2026-08-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0017_socioaviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='socioaviso',
            name='resuelto',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='socioaviso',
            name='resuelto_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socioaviso',
            name='resuelto_por',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
