# Generated by Django 5.2.16 on 2026-08-15 02:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0018_socioaviso_resuelto_socioaviso_resuelto_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasoPendiente',
            fields=[
                ('id_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('molinete_key', models.CharField(max_length=40)),
                ('molinete_nombre', models.CharField(blank=True, default='', max_length=60)),
                ('door_id', models.IntegerField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, default='', max_length=12)),
                ('iniciado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_en', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Paso pendiente',
                'verbose_name_plural': 'Pasos pendientes',
                'db_table': 'acs_paso_pendiente',
            },
        ),
        migrations.AddField(
            model_name='biostaraccessevent',
            name='conflicto_molinete',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='externalaccesslogentry',
            name='conflicto_molinete',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
