# Generated by Django 5.2.16 on 2026-09-03 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0019_pasopendiente_biostaraccessevent_conflicto_molinete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocioAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.BigIntegerField(db_index=True)),
                ('fecha', models.DateTimeField(db_index=True)),
                ('origen', models.CharField(default='credencial', max_length=12)),
                ('referencia', models.CharField(max_length=48, unique=True)),
                ('permitido', models.BooleanField(default=False)),
                ('resultado', models.CharField(blank=True, default='', max_length=4)),
                ('mensaje', models.CharField(blank=True, default='', max_length=255)),
                ('motivo_code', models.IntegerField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, default='', max_length=255)),
                ('puerta', models.CharField(blank=True, default='', max_length=80)),
                ('molinete', models.CharField(blank=True, default='', max_length=60)),
                ('id_acceso', models.IntegerField(blank=True, null=True)),
                ('id_controlador', models.IntegerField(blank=True, null=True)),
                ('device_id', models.BigIntegerField(blank=True, null=True)),
                ('conflicto_molinete', models.CharField(blank=True, default='', max_length=60)),
                ('creado_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Acceso de socio (historial)',
                'verbose_name_plural': 'Accesos de socios (historial)',
                'db_table': 'socio_acceso',
                'ordering': ('-fecha', '-id'),
                'indexes': [models.Index(fields=['id_cliente', '-fecha'], name='socio_acceso_cli_fecha'), models.Index(fields=['-fecha'], name='socio_acceso_fecha')],
            },
        ),
    ]
