# Generated by Django 5.2.16 on 2026-09-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0020_socioacceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioacceso',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='socioacceso',
            name='id_cliente',
            field=models.BigIntegerField(),
        ),
    ]
