# Generated by Django 5.2.12 on 2026-09-30 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0021_alter_socioacceso_fecha_alter_socioacceso_id_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField(unique=True)),
                ('foto_fecha', models.DateTimeField(blank=True, null=True)),
                ('enrolado_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Rostro enrolado en BioStar',
                'verbose_name_plural': 'Rostros enrolados en BioStar',
                'db_table': 'access_control_face_enrollment',
            },
        ),
    ]
