# Generated by Django 5.1.15 on 2026-02-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id_cliente",
                    models.IntegerField(
                        db_column="Id_Cliente", primary_key=True, serialize=False
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True, db_column="Razon_Social", max_length=100, null=True
                    ),
                ),
                (
                    "apellido",
                    models.CharField(
                        blank=True, db_column="Apellido", max_length=100, null=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True, db_column="Nombre", max_length=100, null=True
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True, db_column="Sexo", max_length=1, null=True
                    ),
                ),
                (
                    "fecha_nac",
                    models.DateTimeField(blank=True, db_column="Fecha_Nac", null=True),
                ),
                (
                    "id_tipo_doc",
                    models.CharField(
                        blank=True, db_column="Id_Tipo_Doc", max_length=3, null=True
                    ),
                ),
                (
                    "doc_nro",
                    models.BigIntegerField(blank=True, db_column="Doc_Nro", null=True),
                ),
                (
                    "ingresos_brutos",
                    models.CharField(
                        blank=True,
                        db_column="Ingresos_Brutos",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, db_column="Direccion", max_length=100, null=True
                    ),
                ),
                (
                    "cp",
                    models.CharField(
                        blank=True, db_column="Cp", max_length=10, null=True
                    ),
                ),
                (
                    "id_pais",
                    models.CharField(
                        blank=True, db_column="Id_Pais", max_length=3, null=True
                    ),
                ),
                (
                    "id_provincia",
                    models.CharField(
                        blank=True, db_column="Id_Provincia", max_length=3, null=True
                    ),
                ),
                (
                    "provincia_descrip",
                    models.CharField(
                        blank=True,
                        db_column="Provincia_Descrip",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "id_localidad",
                    models.IntegerField(
                        blank=True, db_column="Id_Localidad", null=True
                    ),
                ),
                (
                    "localidad_descrip",
                    models.CharField(
                        blank=True,
                        db_column="Localidad_Descrip",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("fax", models.TextField(blank=True, db_column="Fax", null=True)),
                (
                    "cuit",
                    models.CharField(
                        blank=True, db_column="Cuit", max_length=19, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="Email", max_length=600, null=True
                    ),
                ),
                (
                    "activo",
                    models.SmallIntegerField(blank=True, db_column="Activo", null=True),
                ),
                (
                    "id_estado_cliente",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Estado_Cliente", null=True
                    ),
                ),
                (
                    "id_grupo_afinidad",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Grupo_Afinidad", null=True
                    ),
                ),
                (
                    "porc_desc_especial",
                    models.DecimalField(
                        blank=True,
                        db_column="Porc_DescEspecial",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "id_lista_precio",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Lista_Precio", null=True
                    ),
                ),
                (
                    "id_vendedor",
                    models.CharField(
                        blank=True, db_column="Id_Vendedor", max_length=10, null=True
                    ),
                ),
                (
                    "id_transportista",
                    models.CharField(
                        blank=True,
                        db_column="Id_Transportista",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "bonif",
                    models.DecimalField(
                        blank=True,
                        db_column="Bonif",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "id_cond_pago",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Cond_Pago", null=True
                    ),
                ),
                (
                    "cred_ctacte",
                    models.DecimalField(
                        blank=True,
                        db_column="Cred_CtaCte",
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "cred_che_pro",
                    models.DecimalField(
                        blank=True,
                        db_column="Cred_ChePro",
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "cred_che_ter",
                    models.DecimalField(
                        blank=True,
                        db_column="Cred_CheTer",
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "id_iva",
                    models.CharField(
                        blank=True, db_column="Id_Iva", max_length=3, null=True
                    ),
                ),
                (
                    "cte",
                    models.CharField(
                        blank=True, db_column="CTE", max_length=50, null=True
                    ),
                ),
                (
                    "id_concepto",
                    models.IntegerField(blank=True, db_column="Id_Concepto", null=True),
                ),
                (
                    "id_cta_banco",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Cta_Banco", null=True
                    ),
                ),
                (
                    "id_zona",
                    models.CharField(
                        blank=True, db_column="Id_Zona", max_length=5, null=True
                    ),
                ),
                (
                    "observacion",
                    models.TextField(blank=True, db_column="Observacion", null=True),
                ),
                (
                    "id_cliente_externo",
                    models.CharField(
                        blank=True,
                        db_column="Id_Cliente_Externo",
                        max_length=14,
                        null=True,
                    ),
                ),
                (
                    "id_transporte",
                    models.IntegerField(
                        blank=True, db_column="Id_Transporte", null=True
                    ),
                ),
                (
                    "id_alias_cta_cont_venta",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Alias_Cta_Cont_Venta", null=True
                    ),
                ),
                (
                    "mercado",
                    models.CharField(
                        blank=True, db_column="Mercado", max_length=1, null=True
                    ),
                ),
                (
                    "observa_fact",
                    models.TextField(blank=True, db_column="Observa_Fact", null=True),
                ),
                (
                    "entre_calle_1",
                    models.CharField(
                        blank=True, db_column="Entre_Calle_1", max_length=35, null=True
                    ),
                ),
                (
                    "entre_calle_2",
                    models.CharField(
                        blank=True, db_column="Entre_Calle_2", max_length=35, null=True
                    ),
                ),
                (
                    "plano_nro",
                    models.CharField(
                        blank=True, db_column="Plano_Nro", max_length=10, null=True
                    ),
                ),
                (
                    "plano_matriz",
                    models.CharField(
                        blank=True, db_column="Plano_Matriz", max_length=10, null=True
                    ),
                ),
                (
                    "id_cobrador",
                    models.CharField(
                        blank=True, db_column="Id_Cobrador", max_length=10, null=True
                    ),
                ),
                (
                    "id_motivo_est",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Motivo_Est", null=True
                    ),
                ),
                (
                    "id_tipo_cli",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Tipo_Cli", null=True
                    ),
                ),
                (
                    "id_dep_fisico",
                    models.CharField(
                        blank=True, db_column="Id_Dep_Fisico", max_length=3, null=True
                    ),
                ),
                (
                    "id_dep_logico",
                    models.CharField(
                        blank=True, db_column="Id_Dep_Logico", max_length=3, null=True
                    ),
                ),
                (
                    "id_tarjeta",
                    models.CharField(
                        blank=True, db_column="Id_Tarjeta", max_length=10, null=True
                    ),
                ),
                (
                    "id_banco",
                    models.IntegerField(blank=True, db_column="Id_Banco", null=True),
                ),
                (
                    "tar_nro",
                    models.CharField(
                        blank=True, db_column="Tar_Nro", max_length=50, null=True
                    ),
                ),
                (
                    "tar_fecha_vence",
                    models.DateTimeField(
                        blank=True, db_column="Tar_Fecha_Vence", null=True
                    ),
                ),
                (
                    "tar_titular",
                    models.CharField(
                        blank=True, db_column="Tar_Titular", max_length=50, null=True
                    ),
                ),
                (
                    "direccion_cob",
                    models.CharField(
                        blank=True, db_column="Direccion_Cob", max_length=100, null=True
                    ),
                ),
                (
                    "cp_cob",
                    models.CharField(
                        blank=True, db_column="Cp_Cob", max_length=10, null=True
                    ),
                ),
                (
                    "id_pais_cob",
                    models.CharField(
                        blank=True, db_column="Id_Pais_Cob", max_length=3, null=True
                    ),
                ),
                (
                    "id_provincia_cob",
                    models.CharField(
                        blank=True,
                        db_column="Id_Provincia_Cob",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "provincia_descrip_cob",
                    models.CharField(
                        blank=True,
                        db_column="Provincia_Descrip_Cob",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "id_localidad_cob",
                    models.IntegerField(
                        blank=True, db_column="Id_Localidad_Cob", null=True
                    ),
                ),
                (
                    "localidad_descrip_cob",
                    models.CharField(
                        blank=True,
                        db_column="Localidad_Descrip_Cob",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "entre_calle_1_cob",
                    models.CharField(
                        blank=True,
                        db_column="Entre_Calle_1_Cob",
                        max_length=35,
                        null=True,
                    ),
                ),
                (
                    "entre_calle_2_cob",
                    models.CharField(
                        blank=True,
                        db_column="Entre_Calle_2_Cob",
                        max_length=35,
                        null=True,
                    ),
                ),
                (
                    "plano_nro_cob",
                    models.CharField(
                        blank=True, db_column="Plano_Nro_Cob", max_length=10, null=True
                    ),
                ),
                (
                    "plano_matriz_cob",
                    models.CharField(
                        blank=True,
                        db_column="Plano_Matriz_Cob",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "fecha_ven_trib",
                    models.DateTimeField(
                        blank=True, db_column="Fecha_Ven_Trib", null=True
                    ),
                ),
                (
                    "web",
                    models.CharField(
                        blank=True, db_column="Web", max_length=254, null=True
                    ),
                ),
                (
                    "id_cliente_ref",
                    models.IntegerField(
                        blank=True, db_column="Id_Cliente_Ref", null=True
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateTimeField(blank=True, db_column="Fecha_Alta", null=True),
                ),
                (
                    "fecha_baja",
                    models.DateTimeField(blank=True, db_column="Fecha_Baja", null=True),
                ),
                (
                    "id_centro_costo",
                    models.CharField(
                        blank=True,
                        db_column="Id_Centro_Costo",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "id_promotor",
                    models.CharField(
                        blank=True, db_column="Id_Promotor", max_length=10, null=True
                    ),
                ),
                (
                    "nombre_fantasia",
                    models.CharField(
                        blank=True,
                        db_column="Nombre_Fantasia",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "id_cond_vta",
                    models.CharField(
                        blank=True, db_column="Id_Cond_Vta", max_length=10, null=True
                    ),
                ),
                (
                    "id_puerto",
                    models.CharField(
                        blank=True, db_column="Id_Puerto", max_length=3, null=True
                    ),
                ),
                (
                    "id_calle",
                    models.IntegerField(blank=True, db_column="Id_Calle", null=True),
                ),
                ("nro", models.IntegerField(blank=True, db_column="Nro", null=True)),
                (
                    "depto",
                    models.CharField(
                        blank=True, db_column="Depto", max_length=10, null=True
                    ),
                ),
                (
                    "fecha_modif",
                    models.DateTimeField(
                        blank=True, db_column="Fecha_Modif", null=True
                    ),
                ),
                (
                    "foto",
                    models.CharField(
                        blank=True, db_column="Foto", max_length=254, null=True
                    ),
                ),
                (
                    "latitud",
                    models.DecimalField(
                        blank=True,
                        db_column="Latitud",
                        decimal_places=7,
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "longitud",
                    models.DecimalField(
                        blank=True,
                        db_column="Longitud",
                        decimal_places=7,
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "id_calle_cob",
                    models.IntegerField(
                        blank=True, db_column="Id_Calle_Cob", null=True
                    ),
                ),
                (
                    "nro_cob",
                    models.IntegerField(blank=True, db_column="Nro_Cob", null=True),
                ),
                (
                    "depto_cob",
                    models.CharField(
                        blank=True, db_column="Depto_Cob", max_length=10, null=True
                    ),
                ),
                (
                    "latitud_cob",
                    models.DecimalField(
                        blank=True,
                        db_column="Latitud_Cob",
                        decimal_places=7,
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "longitud_cob",
                    models.DecimalField(
                        blank=True,
                        db_column="Longitud_Cob",
                        decimal_places=7,
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "id_precio_especial",
                    models.IntegerField(
                        blank=True, db_column="Id_Precio_Especial", null=True
                    ),
                ),
                (
                    "cod_autoriz_trib",
                    models.CharField(
                        blank=True,
                        db_column="Cod_Autoriz_Trib",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "id_alias_cta_cont_venta_dol",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Alias_Cta_Cont_Venta_Dol", null=True
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True, db_column="Estado_Civil", max_length=1, null=True
                    ),
                ),
                (
                    "id_nacionalidad",
                    models.CharField(
                        blank=True, db_column="Id_Nacionalidad", max_length=3, null=True
                    ),
                ),
                (
                    "id_cli_relac",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Cli_Relac", null=True
                    ),
                ),
                (
                    "tipo_persona",
                    models.CharField(
                        blank=True, db_column="Tipo_Persona", max_length=1, null=True
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, db_column="telefono", max_length=900, null=True
                    ),
                ),
                (
                    "calle_descrip",
                    models.CharField(
                        blank=True, db_column="Calle_Descrip", max_length=100, null=True
                    ),
                ),
                (
                    "calle_cob_descrip",
                    models.CharField(
                        blank=True,
                        db_column="Calle_Cob_Descrip",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "imp_aporte",
                    models.DecimalField(
                        blank=True,
                        db_column="Imp_Aporte",
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "fecha_aporte",
                    models.DateTimeField(
                        blank=True, db_column="Fecha_Aporte", null=True
                    ),
                ),
                (
                    "credencial_nro",
                    models.CharField(
                        blank=True, db_column="Credencial_Nro", max_length=30, null=True
                    ),
                ),
                (
                    "credencial_banda1",
                    models.CharField(
                        blank=True,
                        db_column="Credencial_Banda1",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "credencial_banda2",
                    models.CharField(
                        blank=True,
                        db_column="Credencial_Banda2",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "credencial_imp",
                    models.SmallIntegerField(
                        blank=True, db_column="Credencial_Imp", null=True
                    ),
                ),
                (
                    "ult_cuota_paga",
                    models.DateTimeField(
                        blank=True, db_column="Ult_Cuota_Paga", null=True
                    ),
                ),
                (
                    "legajo",
                    models.CharField(
                        blank=True, db_column="Legajo", max_length=30, null=True
                    ),
                ),
                (
                    "credencial_entrega",
                    models.DateTimeField(
                        blank=True, db_column="Credencial_Entrega", null=True
                    ),
                ),
                (
                    "id_unid_negocio",
                    models.CharField(
                        blank=True,
                        db_column="Id_Unid_Negocio",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "clave_web",
                    models.CharField(
                        blank=True, db_column="Clave_Web", max_length=30, null=True
                    ),
                ),
                (
                    "flag_anmat",
                    models.SmallIntegerField(
                        blank=True, db_column="Flag_Anmat", null=True
                    ),
                ),
                (
                    "nro_anmat",
                    models.CharField(
                        blank=True, db_column="Nro_Anmat", max_length=26, null=True
                    ),
                ),
                (
                    "tar_cuit",
                    models.CharField(
                        blank=True, db_column="Tar_Cuit", max_length=19, null=True
                    ),
                ),
                (
                    "id_anmat",
                    models.CharField(
                        blank=True, db_column="Id_Anmat", max_length=3, null=True
                    ),
                ),
                (
                    "coef_comi_vta",
                    models.DecimalField(
                        blank=True,
                        db_column="Coef_Comi_Vta",
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "coef_comi_cobros",
                    models.DecimalField(
                        blank=True,
                        db_column="Coef_Comi_Cobros",
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "email_cob",
                    models.CharField(
                        blank=True, db_column="Email_Cob", max_length=600, null=True
                    ),
                ),
                (
                    "recorrido_cob",
                    models.IntegerField(
                        blank=True, db_column="Recorrido_Cob", null=True
                    ),
                ),
                (
                    "tar_fecha_alta",
                    models.DateTimeField(
                        blank=True, db_column="Tar_Fecha_Alta", null=True
                    ),
                ),
                (
                    "tar_fecha_baja",
                    models.DateTimeField(
                        blank=True, db_column="Tar_Fecha_Baja", null=True
                    ),
                ),
                (
                    "imp_fac_max_mes",
                    models.DecimalField(
                        blank=True,
                        db_column="Imp_Fac_Max_Mes",
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "email_web",
                    models.CharField(
                        blank=True, db_column="Email_Web", max_length=300, null=True
                    ),
                ),
                (
                    "tel_movil",
                    models.CharField(
                        blank=True, db_column="Tel_Movil", max_length=20, null=True
                    ),
                ),
                (
                    "flag_tel_movil_verif",
                    models.SmallIntegerField(
                        blank=True, db_column="Flag_Tel_Movil_Verif", null=True
                    ),
                ),
                (
                    "flag_comunic_sms",
                    models.SmallIntegerField(
                        blank=True, db_column="Flag_Comunic_Sms", null=True
                    ),
                ),
                (
                    "flag_comunic_email",
                    models.SmallIntegerField(
                        blank=True, db_column="Flag_Comunic_Email", null=True
                    ),
                ),
                (
                    "carpeta",
                    models.CharField(
                        blank=True, db_column="Carpeta", max_length=256, null=True
                    ),
                ),
                (
                    "id_emp_area",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Emp_Area", null=True
                    ),
                ),
                (
                    "id_ar_arba_cot_tipo_dom_nro",
                    models.CharField(
                        blank=True,
                        db_column="Id_AR_ARBA_COT_Tipo_Dom_Nro",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "dir_entrega_numero",
                    models.SmallIntegerField(
                        blank=True, db_column="Dir_Entrega_Numero", null=True
                    ),
                ),
                (
                    "dir_entrega_piso",
                    models.CharField(
                        blank=True,
                        db_column="Dir_Entrega_Piso",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "dir_entrega_dto",
                    models.CharField(
                        blank=True, db_column="Dir_Entrega_Dto", max_length=4, null=True
                    ),
                ),
                (
                    "dir_entrega_barrio",
                    models.CharField(
                        blank=True,
                        db_column="Dir_Entrega_Barrio",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "dir_entrega_cp",
                    models.CharField(
                        blank=True, db_column="Dir_Entrega_CP", max_length=8, null=True
                    ),
                ),
                (
                    "dir_entrega_localidad",
                    models.CharField(
                        blank=True,
                        db_column="Dir_Entrega_Localidad",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "id_cliente_grupo",
                    models.IntegerField(
                        blank=True, db_column="Id_Cliente_Grupo", null=True
                    ),
                ),
                (
                    "id_usuario_alta",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Usuario_Alta", null=True
                    ),
                ),
                (
                    "id_usuario_baja",
                    models.SmallIntegerField(
                        blank=True, db_column="Id_Usuario_Baja", null=True
                    ),
                ),
                (
                    "flag_fact_no_imprimir",
                    models.SmallIntegerField(
                        blank=True, db_column="Flag_Fact_No_Imprimir", null=True
                    ),
                ),
                (
                    "flag_fact_no_mail",
                    models.SmallIntegerField(
                        blank=True, db_column="Flag_Fact_No_Mail", null=True
                    ),
                ),
                (
                    "id_facebook",
                    models.CharField(
                        blank=True, db_column="Id_Facebook", max_length=255, null=True
                    ),
                ),
                (
                    "id_instagram",
                    models.CharField(
                        blank=True, db_column="Id_Instagram", max_length=255, null=True
                    ),
                ),
                (
                    "id_twitter",
                    models.CharField(
                        blank=True, db_column="Id_Twitter", max_length=255, null=True
                    ),
                ),
                (
                    "id_linkedin",
                    models.CharField(
                        blank=True, db_column="Id_Linkedin", max_length=255, null=True
                    ),
                ),
                (
                    "id_ogle",
                    models.CharField(
                        blank=True, db_column="Id_ogle", max_length=255, null=True
                    ),
                ),
                (
                    "id_microsoft",
                    models.CharField(
                        blank=True, db_column="Id_Microsoft", max_length=255, null=True
                    ),
                ),
                (
                    "fecha_app",
                    models.DateTimeField(blank=True, db_column="Fecha_App", null=True),
                ),
                (
                    "id_google",
                    models.CharField(
                        blank=True, db_column="Id_Google", max_length=255, null=True
                    ),
                ),
                (
                    "z_id_invitado_2020_verano",
                    models.IntegerField(
                        blank=True, db_column="z_Id_Invitado_2020__Verano", null=True
                    ),
                ),
                (
                    "pasap_nro",
                    models.CharField(
                        blank=True, db_column="Pasap_Nro", max_length=50, null=True
                    ),
                ),
                (
                    "fecha_web_registro",
                    models.DateTimeField(
                        blank=True, db_column="Fecha_Web_Registro", null=True
                    ),
                ),
                (
                    "fecha_web_ult_ingreso",
                    models.DateTimeField(
                        blank=True, db_column="Fecha_Web_Ult_Ingreso", null=True
                    ),
                ),
                (
                    "flag_fac_dir_cli",
                    models.SmallIntegerField(
                        blank=True, db_column="Flag_Fac_Dir_Cli", null=True
                    ),
                ),
                (
                    "fecha_sinc_event",
                    models.DateTimeField(
                        blank=True, db_column="Fecha_Sinc_Event", null=True
                    ),
                ),
                (
                    "fecha_ult_modif_dp",
                    models.DateTimeField(
                        blank=True, db_column="Fecha_Ult_Modif_DP", null=True
                    ),
                ),
                (
                    "login_codigo_acceso",
                    models.CharField(
                        blank=True,
                        db_column="Login_Codigo_Acceso",
                        max_length=150,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "Clientes",
            },
        ),
    ]
