# Generated by Django 5.1.15 on 2026-03-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessDoor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doors",
                        to="institutions.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site__name", "name"],
                "unique_together": {("site", "code")},
            },
        ),
        migrations.CreateModel(
            name="AccessZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ring_code", models.CharField(max_length=2)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="institutions.accesszone",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="institutions.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site__name", "ring_code"],
                "unique_together": {("site", "ring_code")},
            },
        ),
        migrations.CreateModel(
            name="DoorDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("turnstile", "Molinete"),
                            ("facial", "Facial"),
                            ("credential_reader", "Lector de credenciales"),
                        ],
                        max_length=32,
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=128)),
                ("serial_number", models.CharField(blank=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("entry", "Entrada"),
                            ("exit", "Salida"),
                            ("both", "Ambos"),
                        ],
                        default="entry",
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "door",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="institutions.accessdoor",
                    ),
                ),
            ],
            options={
                "ordering": ["door__name", "id"],
            },
        ),
        migrations.CreateModel(
            name="DoorZoneControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("entry", "Entrada"),
                            ("exit", "Salida"),
                            ("both", "Ambos"),
                        ],
                        default="both",
                        max_length=8,
                    ),
                ),
                (
                    "door",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_controls",
                        to="institutions.accessdoor",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="door_controls",
                        to="institutions.accesszone",
                    ),
                ),
            ],
            options={
                "unique_together": {("door", "zone")},
            },
        ),
    ]
