# Generated by Django 5.2.12 on 2026-07-21 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_accessdoor_accesszone_doordevice_doorzonecontrol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessdoor',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='accessdoor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accessdoor',
            name='xsys_id_acceso',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessdoor',
            name='code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='accessdoor',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='institutions.site'),
        ),
        migrations.CreateModel(
            name='DoorTurnstileGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('id_controladores', models.JSONField(blank=True, default=list)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnstile_groups', to='institutions.accessdoor')),
            ],
            options={
                'ordering': ['door__name', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DoorController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_controlador', models.IntegerField(db_index=True)),
                ('orden', models.IntegerField(default=0)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='institutions.accessdoor')),
            ],
            options={
                'ordering': ['door__name', 'orden', 'id'],
                'unique_together': {('door', 'id_controlador')},
            },
        ),
    ]
