# Generated by Django 5.2.16 on 2026-07-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_alter_accessdoor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorturnstilegroup',
            name='biostar_device_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
