from django.urls import path
from rest_framework.routers import DefaultRouter

from access_control.api.v1.api_views import (
    AccessCheckAPI,
    AnsesCandidatesAPI,
    AnsesProcessedExportAPI,
    AnsesVerifyAPI,
    AnsesVerifyFilteredAPI,
    AnsesVerifyFilteredStatusAPI,
    Api3000CommandCatalogAPI,
    Api3000ExecuteCommandAPI,
    Api3000PingAPI,
    BioStarDeviceDetailAPI,
    BioStarDeviceDoorsAPI,
    BioStarDeviceGroupListAPI,
    BioStarDeviceListAPI,
    BioStarDeviceLockAPI,
    BioStarDeviceMoveGroupAPI,
    BioStarDeviceRebootAPI,
    BioStarDeviceRenameAPI,
    BioStarDeviceStatsAPI,
    BioStarDeviceSyncAPI,
    BioStarDeviceUserAddAPI,
    BioStarDeviceUserdataAPI,
    BioStarDeviceUserRemoveAPI,
    BioStarDeviceUsersAPI,
    BioStarDeviceUsersClearAPI,
    BioStarDoorActionAPI,
    BioStarEnrollFaceAPI,
    BioStarUserForceLoadAPI,
    BioStarUserListAPI,
    BioStarUserLookupAPI,
    BioStarUserSearchAPI,
    BioStarUserSyncAPI,
    ExternalAccessLogSyncAPI,
    AvisoResolverAPI,
    IntelektronDeviceListAPI,
    IntelektronEventsAPI,
    SocioAvisoAPI,
    WhitelistBatchCreateAPI,
)
from access_control.api.v1.intelectron_api_views import (
    Api3000CommandAPI as Api3000ServiceCommandAPI,
    Api3000PingAPI as Api3000ServicePingAPI,
)
from access_control.views import (
    AccessByCategoryReportView,
    AccessBySiteReportView,
    AccessDenialsReportView,
    AccessEventViewSet,
    AccessHeatmapReportView,
    ExternalAccessLogView,
    ParkingClienteLookupView,
    ParkingMovementMarkExitView,
    ParkingMovementView,
    WhitelistEntryViewSet,
)

router = DefaultRouter()
router.register(r"whitelist", WhitelistEntryViewSet)
router.register(r"access-events", AccessEventViewSet)

urlpatterns = router.urls + [

    path("acs/test/ping/", Api3000ServicePingAPI.as_view(), name="acs_test_ping_api"),
    path("acs/test/command/", Api3000ServiceCommandAPI.as_view(), name="acs_test_command_api"),

    path("api3000/catalog/", Api3000CommandCatalogAPI.as_view(), name="api3000_catalog_api"),
    path("api3000/ping/", Api3000PingAPI.as_view(), name="api3000_ping_api"),
    path("api3000/execute/", Api3000ExecuteCommandAPI.as_view(), name="api3000_execute_api"),
    path("intelektron/devices/", IntelektronDeviceListAPI.as_view(), name="intelektron_devices_api"),
    path("intelektron/events/", IntelektronEventsAPI.as_view(), name="intelektron_events_api"),
    path("parking/client-lookup/", ParkingClienteLookupView.as_view(), name="parking_client_lookup"),
    path("parking/movements/", ParkingMovementView.as_view(), name="parking_movements_api"),
    path("parking/movements/<int:movement_id>/mark-exit/", ParkingMovementMarkExitView.as_view(), name="parking_movement_mark_exit_api"),
    path("biostar/devices/", BioStarDeviceListAPI.as_view(), name="biostar_devices_list_api"),
    path("biostar/devices/sync/", BioStarDeviceSyncAPI.as_view(), name="biostar_devices_sync_api"),
    path("biostar/devices/stats/", BioStarDeviceStatsAPI.as_view(), name="biostar_devices_stats_api"),
    path("biostar/enroll-face/", BioStarEnrollFaceAPI.as_view(), name="biostar_enroll_face_api"),
    path(
        "biostar/devices/<int:device_id>/users/",
        BioStarDeviceUsersAPI.as_view(),
        name="biostar_device_users_api",
    ),
    path(
        "biostar/devices/<int:device_id>/discover_userdata/",
        BioStarDeviceUserdataAPI.as_view(),
        name="biostar_device_userdata_api",
    ),
    # --- Administración de equipos ---
    path("biostar/device-groups/", BioStarDeviceGroupListAPI.as_view(), name="biostar_device_groups_api"),
    path(
        "biostar/devices/<int:device_id>/detail/",
        BioStarDeviceDetailAPI.as_view(),
        name="biostar_device_detail_api",
    ),
    path(
        "biostar/devices/<int:device_id>/rename/",
        BioStarDeviceRenameAPI.as_view(),
        name="biostar_device_rename_api",
    ),
    path(
        "biostar/devices/<int:device_id>/move-group/",
        BioStarDeviceMoveGroupAPI.as_view(),
        name="biostar_device_move_group_api",
    ),
    path(
        "biostar/devices/<int:device_id>/reboot/",
        BioStarDeviceRebootAPI.as_view(),
        name="biostar_device_reboot_api",
    ),
    path(
        "biostar/devices/<int:device_id>/lock/",
        BioStarDeviceLockAPI.as_view(),
        {"action": "lock"},
        name="biostar_device_lock_api",
    ),
    path(
        "biostar/devices/<int:device_id>/unlock/",
        BioStarDeviceLockAPI.as_view(),
        {"action": "unlock"},
        name="biostar_device_unlock_api",
    ),
    path(
        "biostar/devices/<int:device_id>/doors/",
        BioStarDeviceDoorsAPI.as_view(),
        name="biostar_device_doors_api",
    ),
    path(
        "biostar/doors/<int:door_id>/<str:action>/",
        BioStarDoorActionAPI.as_view(),
        name="biostar_door_action_api",
    ),
    path(
        "biostar/devices/<int:device_id>/users/add/",
        BioStarDeviceUserAddAPI.as_view(),
        name="biostar_device_user_add_api",
    ),
    path(
        "biostar/devices/<int:device_id>/users/remove/",
        BioStarDeviceUserRemoveAPI.as_view(),
        name="biostar_device_user_remove_api",
    ),
    path(
        "biostar/devices/<int:device_id>/users/clear/",
        BioStarDeviceUsersClearAPI.as_view(),
        name="biostar_device_users_clear_api",
    ),
    path("biostar/users/", BioStarUserListAPI.as_view(), name="biostar_users_list_api"),
    path("biostar/users/lookup/", BioStarUserLookupAPI.as_view(), name="biostar_users_lookup_api"),
    path("biostar/users/search/", BioStarUserSearchAPI.as_view(), name="biostar_users_search_api"),
    path("biostar/users/<int:id_cliente>/force-load/", BioStarUserForceLoadAPI.as_view(), name="biostar_user_force_load_api"),
    path("socios/<int:id_cliente>/avisos/", SocioAvisoAPI.as_view(), name="socio_avisos_api"),
    path("avisos/<int:aviso_id>/resolver/", AvisoResolverAPI.as_view(), name="aviso_resolver_api"),
    path("biostar/users/sync/", BioStarUserSyncAPI.as_view(), name="biostar_users_sync_api"),
    path(
        "external-access/sync/",
        ExternalAccessLogSyncAPI.as_view(),
        name="external_access_sync_api",
    ),
    path(
        "external-access/latest/",
        ExternalAccessLogView.as_view(),
        name="external-access-latest",
    ),
    path(
        "whitelist/batch/",
        WhitelistBatchCreateAPI.as_view(),
        name="whitelist_batch_create_api",
    ),
    path("access-check/", AccessCheckAPI.as_view(), name="access_check_api"),
    path("reports/access-by-category/", AccessByCategoryReportView.as_view(), name="report_access_by_category"),
    path("reports/access-by-site/", AccessBySiteReportView.as_view(), name="report_access_by_site"),
    path("reports/access-heatmap/", AccessHeatmapReportView.as_view(), name="report_access_heatmap"),
    path("reports/access-denials/", AccessDenialsReportView.as_view(), name="report_access_denials"),
    path("anses/candidates/", AnsesCandidatesAPI.as_view(), name="anses_candidates_api"),
    path("anses/processed/export/", AnsesProcessedExportAPI.as_view(), name="anses_processed_export_api"),
    path("anses/verify/", AnsesVerifyAPI.as_view(), name="anses_verify_api"),
    path("anses/verify-filtered/", AnsesVerifyFilteredAPI.as_view(), name="anses_verify_filtered_api"),
    path("anses/verify-filtered/<str:job_id>/", AnsesVerifyFilteredStatusAPI.as_view(), name="anses_verify_filtered_status_api"),
]
